eureka:
  client:
    service-url:
      defaultZone: http://yushan-eureka-registry:8761/eureka/

spring:
  cloud:
    config:
      server:
        # Native Backend (for local development/testing)
        native:
          search-locations: classpath:/configs,file:./configs
        # Disable Git backend completely
        git:
          enabled: false