eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maugus0/yushan-config-server.git
          default-label: main