spring:
  application:
    name: gamification-service

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    time-zone: ${TIMEZONE:Asia/Singapore}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:yushan_gamification}
    username: ${DB_USERNAME:yushan_gamification}
    password: ${DB_PASSWORD:change_me_in_production}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000

  # JPA/Hibernate Configuration - Disabled (using MyBatis only)
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  # MyBatis Configuration
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.yushan.gamification_service.entity
    config-location: classpath:config/mybatis-config.xml

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: gamification-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: gamification-service
      retries: 3
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432
      acks: all
      enable-idempotence: true
      compression-type: snappy
      request-timeout-ms: 30000
      delivery-timeout-ms: 120000
      topic:
        achievement-events: achievement-events
        level-up-events: level-up-events
        reward-events: reward-events

# Server Configuration
server:
  port: ${SERVER_PORT:8085}
  servlet:
    context-path: /
  compression:
    enabled: true

# Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    metadata-map:
      version: 1.0.0
      description: Gamification service for achievements, badges, and rewards

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

# Logging Configuration
logging:
  level:
    com.yushan.gamification: ${LOG_LEVEL_GAMIFICATION:DEBUG}
    org.springframework.cloud: ${LOG_LEVEL_SPRING_CLOUD:INFO}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_HIBERNATE_BINDER:TRACE}
    com.yushan.gamification_service.security: ${LOG_LEVEL_SECURITY:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY:DEBUG}
    com.yushan.gamification_service.util.JwtUtil: ${LOG_LEVEL_JWT:DEBUG}

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:yushan-micro-service-secret-key-for-jwt-token-generation-and-validation-2024}
  issuer: ${JWT_ISSUER:yushan-micro-service}
  algorithm: ${JWT_ALGORITHM:HS256}

# Gamification Configuration
gamification:
  rewards:
    daily-login-exp: ${DAILY_LOGIN_EXP:5}
    daily-login-yuan: ${DAILY_LOGIN_YUAN:1}
    comment-exp: ${COMMENT_EXP:5}
    review-exp: ${REVIEW_EXP:5}